<a href="https://colab.research.google.com/github/francomanca93/fundamentos-algebra-lineal/blob/operaciones-basicas/2_Operaciones_b%C3%A1sicas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Realiza operaciones básicas

## Dimensión de un escalar, vector, matriz o tensor

Para saber la dimensión de un objeto utilizaremos el método **.shape** de la librería **numpy**.

* **.size** : devuelve el total de los elementos de un vector, matriz o tensor.
* **.shape**: devuelve la dimensión de un vector, matriz y tensor.

In [1]:
import numpy as np

In [8]:
escalar = 5.679
vector = np.array([1, 2, 3])
matriz = np. array([[1, 2], [3, 4]])
tensor = np. array([
                    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                    [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
                    [[21, 22, 23], [24, 25, 26], [27, 28, 29]]
                  ])

In [22]:
print(escalar)

5.679


In [10]:
escalar.shape

AttributeError: ignored

Un escalar no tiene dimensiones. Es un número unicamente. Por tenemos un error del tipo **AttributeError**.

In [29]:
print(vector)
print('dimensón: ', vector.shape)
print('tamaño del vector, cantidad de elementos: ', vector.size)

[1 2 3]
dimensón:  (3,)
tamaño del vector, cantidad de elementos:  3


In [30]:
print(matriz)
print('dimensón: ', matriz.shape)
print('tamaño del vector, cantidad de elementos: ', matriz.size)

[[1 2]
 [3 4]]
dimensón:  (2, 2)
tamaño del vector, cantidad de elementos:  4


In [31]:
print(tensor.shape)
print('dimensón: ', tensor.shape)
print('tamaño del vector, cantidad de elementos: ', tensor.size)

(3, 3, 3)
dimensón:  (3, 3, 3)
tamaño del vector, cantidad de elementos:  27


En las dimensiones del tensor, la primera posición se refiere al número de matrices, el segundo a las filas y el tercero a las columnas:

* (numero de matrices, numero_filas, número_columnas)

In [32]:
tensor2 = np.array([
    [[1,3],[4,6],[6,8]],
    [[11,13],[14,16],[17,19]],
    [[21,23],[24,26],[27,28]],
    [[32,33],[34,36],[37,39]],
])
print(tensor2)
print('dimensón: ', tensor2.shape)
print('tamaño del vector, cantidad de elementos: ', tensor2.size)

[[[ 1  3]
  [ 4  6]
  [ 6  8]]

 [[11 13]
  [14 16]
  [17 19]]

 [[21 23]
  [24 26]
  [27 28]]

 [[32 33]
  [34 36]
  [37 39]]]
dimensón:  (4, 3, 2)
tamaño del vector, cantidad de elementos:  24


## Transposición, suma de matrices y escalares

## Suma de matrices y vectores (broadcasting)