<a href="https://colab.research.google.com/github/francomanca93/fundamentos-algebra-lineal/blob/operaciones-basicas/2_Operaciones_b%C3%A1sicas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Realiza operaciones básicas

## Dimensión de un escalar, vector, matriz o tensor

Para saber la dimensión de un objeto utilizaremos el método **.shape** de la librería **numpy**.

* **.size** : devuelve el total de los elementos de un vector, matriz o tensor.
* **.shape**: devuelve la dimensión de un vector, matriz y tensor.

In [6]:
import numpy as np

In [7]:
escalar = 5.679
vector = np.array([1, 2, 3])
matriz = np. array([[1, 2], [3, 4]])
tensor = np. array([
                    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                    [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
                    [[21, 22, 23], [24, 25, 26], [27, 28, 29]]
                  ])

In [8]:
print(escalar)

5.679


In [9]:
escalar.shape

AttributeError: ignored

Un escalar no tiene dimensiones. Es un número unicamente. Por tenemos un error del tipo **AttributeError**.

In [10]:
print(vector)
print('dimensón: ', vector.shape)
print('tamaño del vector, cantidad de elementos: ', vector.size)

[1 2 3]
dimensón:  (3,)
tamaño del vector, cantidad de elementos:  3


In [11]:
print(matriz)
print('dimensón: ', matriz.shape)
print('tamaño del vector, cantidad de elementos: ', matriz.size)

[[1 2]
 [3 4]]
dimensón:  (2, 2)
tamaño del vector, cantidad de elementos:  4


In [12]:
print(tensor.shape)
print('dimensón: ', tensor.shape)
print('tamaño del vector, cantidad de elementos: ', tensor.size)

(3, 3, 3)
dimensón:  (3, 3, 3)
tamaño del vector, cantidad de elementos:  27


En las dimensiones del tensor, la primera posición se refiere al número de matrices, el segundo a las filas y el tercero a las columnas:

* (numero de matrices, numero_filas, número_columnas)

In [13]:
tensor2 = np.array([
    [[1,3],[4,6],[6,8]],
    [[11,13],[14,16],[17,19]],
    [[21,23],[24,26],[27,28]],
    [[32,33],[34,36],[37,39]],
])
print(tensor2)
print('dimensón: ', tensor2.shape)
print('tamaño del vector, cantidad de elementos: ', tensor2.size)

[[[ 1  3]
  [ 4  6]
  [ 6  8]]

 [[11 13]
  [14 16]
  [17 19]]

 [[21 23]
  [24 26]
  [27 28]]

 [[32 33]
  [34 36]
  [37 39]]]
dimensón:  (4, 3, 2)
tamaño del vector, cantidad de elementos:  24


## Transposición, suma de matrices y escalares

Transponer un vector o una matriz es cambiar la fila por columna y viceversa.

![Transpuesta](https://2.bp.blogspot.com/-5USUoNNm5IE/WLvu8wd-q5I/AAAAAAAAaCc/nGOn3LBMYcUv3m9taYP3gPlHUaladFNFQCLcB/s1600/Traspuesta.png)


Para realizar la transpuesta tanto, de un vector como de una matriz o un tensor utilizamos el motodo **.T**.

Si lo que queremos es realizar una **suma de matrices** (IMPORTANTE deben ser si o si de **las misma diemensiones**) simplemente colocamos “+” entre ambas como si estuviesemos sumando numeros. Lo mismo se puede hacer con los tensores pero cada una de las matrices que contenga deben ser de misma dimensiones.

Tambien podemos sumar un escalar a una matriz o un tensor y una matriz a un tensor.



In [14]:
escalar_t = escalar.T

AttributeError: ignored

Esto tiene sentido ya que transponer es cambiar filas por columna y viceversa y un escalar no tiene ni filas ni columnas. Por lo tanto tendremos un **AttributeError**.  

In [15]:
vector_t = vector.T
print('Nuestro vector: ', vector)
print('Vector transpuesta: ', vector_t)

Nuestro vector:  [1 2 3]
Vector transpuesta:  [1 2 3]


Esto tambien tiene sentido, porque un vector tiene una dimensión. Entonces la fila del vector es igual a la columna de ese vector, cuando se hace la transpuesta.

In [16]:
matriz2 = np.array([[1, 2, 3],
                    [4, 5, 6]
                  ])
print('Nuestro vector: \n', matriz2)
print('Dimensión: ', matriz2.shape)

Nuestro vector: 
 [[1 2 3]
 [4 5 6]]
Dimensión:  (2, 3)


In [17]:
matriz2_t = matriz2.T
print('Nuestro vector: \n', matriz2_t)
print('Dimensión: ', matriz2_t.shape)

Nuestro vector: 
 [[1 4]
 [2 5]
 [3 6]]
Dimensión:  (3, 2)


In [18]:
print('Tensor: \n', tensor2)
print('Dimensión: ', tensor2.shape)

Tensor: 
 [[[ 1  3]
  [ 4  6]
  [ 6  8]]

 [[11 13]
  [14 16]
  [17 19]]

 [[21 23]
  [24 26]
  [27 28]]

 [[32 33]
  [34 36]
  [37 39]]]
Dimensión:  (4, 3, 2)


In [19]:
tensor2_t = tensor2.T
print('Tensor transpuesta: \n', tensor2_t)
print('Dimensión: ', tensor2_t.shape)

Tensor transpuesta: 
 [[[ 1 11 21 32]
  [ 4 14 24 34]
  [ 6 17 27 37]]

 [[ 3 13 23 33]
  [ 6 16 26 36]
  [ 8 19 28 39]]]
Dimensión:  (2, 3, 4)


In [27]:
matriz2_t_t = matriz2_t.T
print(matriz2)
print(matriz2_t_t)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


Suma de matrices

In [28]:
A = matriz2
B = matriz2_t

In [29]:
C = A + B

ValueError: ignored

Tenemos un **ValueError** ya que las matrices tienen dimensiones diferentes y no se pueden sumar.

In [31]:
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[6, 5], [4, 3], [2, 1]])
C = A + B
print(A)
print(B)
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[6 5]
 [4 3]
 [2 1]]
[[7 7]
 [7 7]
 [7 7]]


In [33]:
D = matriz + escalar
print(D)

[[6.679 7.679]
 [8.679 9.679]]


In [40]:
matriz_reto = np.array([[1, 2, 3, 4, 5],
                        [1, 2, 3, 4, 5],
                        [1, 2, 3, 4, 5],
                        [1, 2, 3, 4, 5],
                        [1, 2, 3, 4, 5]])
matriz_reto_t = matriz_reto.T

print('Matriz reto: \n', matriz_reto)
print('Matriz transpuesta del reto: \n', matriz_reto_t)

suma_matrices_reto = matriz_reto + matriz_reto_t
print('Suma de matrices reto: \n', suma_matrices_reto)

Matriz reto: 
 [[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
Matriz transpuesta del reto: 
 [[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]
Suma de matrices reto: 
 [[ 2  3  4  5  6]
 [ 3  4  5  6  7]
 [ 4  5  6  7  8]
 [ 5  6  7  8  9]
 [ 6  7  8  9 10]]


## Suma de matrices y vectores (broadcasting)

¿Cuando es posible sumar matrices y vectores con dimensiones distintas? 
Cuando se cumple las reglas de python para hacer broadcasting. 


**Broadcasting**: es extender la matriz o vector de menor tamaño para que se ajuste a la de mayor tamaño.

![alt text](https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png)


In [46]:
escalar = 5.679
vector = np.array([1, 2, 3])
matriz = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

In [47]:
A = vector + matriz

ValueError: ignored

Como dice el error, el vector tiene diferente dimesión que la matriz y por lo tento no se puede hacer broacasting.

Pero si transponemos la matriz, si se podrá.

In [49]:
A = matriz.T + vector
print(A)

[[2 5 8]
 [3 6 9]]


In [52]:
C = matriz + escalar
print(C)

[[ 6.679  7.679]
 [ 8.679  9.679]
 [10.679 11.679]]
