<a href="https://colab.research.google.com/github/francomanca93/fundamentos-algebra-lineal/blob/operaciones-matriciales/3_Operaciones_con_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Operaciones con matrices

## Producto interno entre una matriz y un vector

[Producto escalar](https://es.wikipedia.org/wiki/Producto_escalar)

**Producto interno**, tambien conocido como **producto escalar, producto interior o producto punto**, es una operación algebraica que toma dos secuencias de números de igual longitud (usualmente en la forma de vectores) y retorna un único número. 

In [1]:
import numpy as np

In [6]:
escalar = 5.679
vector = np.array([2, 3])
matriz = np. array([[1, 2], [3, 4], [5, 6]])

In [7]:
A = matriz * vector
B = matriz.dot(vector)

In [10]:
print('Producto elemento a elemento: \n', A)

Producto elemento a elemento: 
 [[ 2  6]
 [ 6 12]
 [10 18]]


Lo que se esta haciendo en este caso es broadcasting. 

In [11]:
print('Producto escalar: \n', B)

Producto escalar: 
 [ 8 18 28]


Se utiliza la función **.dot()** y lo que está pasando en lo siguiente: 

![producto escalar](https://i.imgur.com/cAVzYpx.png)

## Producto interno entre dos matrices

In [14]:
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
B = np.array([[2,3],[5,7],[11,13]])

In [15]:
print('Dimension de A: ', A.shape)
print('Dimension de B: ', B.shape)

Dimension de A:  (4, 3)
Dimension de B:  (3, 2)


In [16]:
C = A.dot(B)

Se puede realizar la operación **A . B** ya que:
* Dimension de A:  (4, **3**)
* Dimension de B:  (**3**, 2)

Los valores en negrita son de la misma dimensión. 



In [18]:
print(C)

[[ 45  56]
 [ 99 125]
 [153 194]
 [207 263]]


In [17]:
D = B.dot(A)

ValueError: ignored

No se puede realizar la operación **B . ** ya que:
* Dimension de B:  (3, **2**)
* Dimension de A:  (**4**, 3)

Los valores en negrita son de diferentes dimensión y eso es lo que nos marca el error **ValueError** 