<a href="https://colab.research.google.com/github/francomanca93/fundamentos-algebra-lineal/blob/especiales/6_Matrices_y_vectores_especiales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrices y vectores especiales



## La matriz diagonal y la matriz simétrica: sus propiedades 

### Matriz diagonal y sus propiedades

La matriz diagonal es aquella que tiene solo numeros en su diagonal.


In [1]:
import numpy as np

In [2]:
vector = np.array([1,2,3,4,5])

matriz = np.diag(vector)

print(matriz)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


Una matriz diagonal no solamente puede ser cuadrada, si no que puede tener otras dimensiones.

In [3]:
print(matriz[0:4, 0:3])

[[1 0 0]
 [0 2 0]
 [0 0 3]
 [0 0 0]]


In [4]:
print(matriz[0:3, 0:4])

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]


Si ahora difinimos una matriz diagonal:

In [6]:
A = np.diag([2,3,4,5])
print(A)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


Algo a tener en cuenta es que al multiplicarlas por un vector no estan siendo una combinacion lineal de las distintas coordenadas sino lo que hace es una ponderacion de los elementos del vector por el cual estoy multiplicando.

In [20]:
v1 = np.array([[1,1,1,1]])

print(v1)

print('Matriz ponderada: \n', A.dot(v1.T))

[[1 1 1 1]]
Matriz ponderada: 
 [[2]
 [3]
 [4]
 [5]]


Otra cosa a tener en cuenta de las matrices diagonales es que para sacar su matriz inversa lo unico que debo realizar es crear una matriz cuyos elementos en la diagonal esten invertidos es decir 1/x. Esto computacionalmente es beneficioso.

In [9]:
A_inv = np.diag([1/2, 1/3, 1/4, 1/5])
print(A_inv)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


Si decimos que la matriz inversa es invertir los numeros de las diagonales se debe cumplir los siguiente: 
* A . A^t = Id

El producto escalar entre una matriz diagonal y su transpuesta diagonal debe ser igual a la matriz identidad. 

In [11]:
identidad = A.dot(A_inv)
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
A_inv_calc = np.linalg.inv(A)
print(A_inv_calc)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


### Matriz simetrica y sus propiedades

Una matriz es simetrica cuando su transpuesta es igual a la misma matriz.

**Recordatorio:** Hacer una transposicion es cambiar filas por columnas.

In [14]:
# Calculamos la transpuesta de la matriz A
print(A.T)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [15]:
print(A)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


Con esto vemos que ambas matrices son iguales, entonces la misma es simetrica y en este caso diagonal. 

Pero no todas las matrices simetricas son diagonales tambien, como en el siguiente ejemplo:

In [17]:
simetrica = np.array([[1,2,3],
                      [2,-1,7],
                      [3,7,11]])
print(simetrica)

[[ 1  2  3]
 [ 2 -1  7]
 [ 3  7 11]]


In [18]:
print(simetrica.T)

[[ 1  2  3]
 [ 2 -1  7]
 [ 3  7 11]]
